datasource:
  jdbc-url: jdbc:postgresql://127.0.0.1:5432/wheremoney
  username: disqo
  password: disqo@pass_123
  pool-size: 30

spring:
  jpa:
    hibernate:
      ddl-auto: update
      show_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

security:
  jwt:
    username: admin
    password: wheremoneyapp@admin_123456
    secret-key: 6jjzadtjrhbuwld8weh2fp2kn8eh
    validity-in-ms: 3600000

session:
  ban-for-in-hours: 48
  max-login-attempts: 5


server:
  port: 8090